# -*- coding: utf-8 -*-
"""app1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bv6R5IcCtCqF2qZeUst6aetozzHmMhUf
"""

import matplotlib
matplotlib.use("Agg")
import streamlit as st
import math
import numpy as np
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from scipy.stats import norm
import warnings
warnings.filterwarnings("ignore")

st.set_page_config(page_title="◈ Options Pricer", layout="wide", page_icon="📐",
                   initial_sidebar_state="collapsed")

C = dict(orange="#FF6600", yellow="#FFD700", green="#00FF41",
         red="#FF3333", blue="#00BFFF", gray="#777777")

st.markdown("""
<style>
  html,body,.stApp{background:#000!important;color:#FFF;}
  section[data-testid="stSidebar"]{display:none;}
  .stTabs [data-baseweb="tab-list"]{background:#000;border-bottom:2px solid #FF6600;gap:3px;}
  .stTabs [data-baseweb="tab"]{background:#0D0D0D;color:#FF6600;border:1px solid #333;
    border-radius:4px 4px 0 0;font-family:monospace;font-weight:bold;padding:6px 18px;}
  .stTabs [aria-selected="true"]{background:#FF6600!important;color:#000!important;}
  .stButton>button{background:#FF6600;color:#000;font-family:monospace;font-weight:bold;border:none;border-radius:4px;padding:6px 20px;}
  .stButton>button:hover{background:#FFD700;}
  .stSelectbox>div>div,.stSlider,.stNumberInput{font-family:monospace;}
  label,.stSlider label,.stNumberInput label{color:#FF6600!important;font-family:monospace!important;font-weight:bold!important;}
  h1,h2,h3{color:#FF6600!important;font-family:monospace!important;}
  .stRadio>label{color:#FF6600!important;font-family:monospace!important;font-weight:bold!important;}
  .stRadio [data-testid="stMarkdownContainer"] p{color:#FFD700;font-family:monospace;}
  div[data-testid="metric-container"]{background:#0D0D0D;border:1px solid #FF6600;
    border-radius:6px;padding:12px 16px;}
  div[data-testid="stMetricValue"]{color:#FFD700!important;font-family:monospace;font-size:1.6rem!important;}
  div[data-testid="stMetricLabel"]{color:#FF6600!important;font-family:monospace;}
  .result-box{background:#0D0D0D;border:1px solid #FF6600;border-radius:6px;
    padding:16px 20px;font-family:Courier New,monospace;margin-bottom:10px;}
  .block-container{padding-top:0.5rem!important;}
</style>""", unsafe_allow_html=True)

# ── MATH CORE ────────────────────────────────────────────────
def bs_params(St, K, r, sigma, T, q=0):
    d1 = (math.log(St/K) + (r - q + 0.5*sigma**2)*T) / (sigma*math.sqrt(T))
    d2 = d1 - sigma*math.sqrt(T)
    return d1, d2

def black_scholes(St, K, sigma, T, r, q=0):
    d1, d2 = bs_params(St, K, r, sigma, T, q)
    dc = math.exp(-r*T) * norm.cdf(d2)
    sc = St*math.exp(-q*T)*norm.cdf(d1) - K*math.exp(-r*T)*norm.cdf(d2)
    dp = math.exp(-r*T) * norm.cdf(-d2)
    sp = K*math.exp(-r*T)*norm.cdf(-d2) - St*math.exp(-q*T)*norm.cdf(-d1)
    # Greeks
    delta_c =  math.exp(-q*T)*norm.cdf(d1)
    delta_p = -math.exp(-q*T)*norm.cdf(-d1)
    gamma   =  math.exp(-q*T)*norm.pdf(d1) / (St*sigma*math.sqrt(T))
    vega    =  St*math.exp(-q*T)*norm.pdf(d1)*math.sqrt(T)/100
    theta_c = (-(St*norm.pdf(d1)*sigma*math.exp(-q*T))/(2*math.sqrt(T))
               - r*K*math.exp(-r*T)*norm.cdf(d2)
               + q*St*math.exp(-q*T)*norm.cdf(d1))/365
    theta_p = (-(St*norm.pdf(d1)*sigma*math.exp(-q*T))/(2*math.sqrt(T))
               + r*K*math.exp(-r*T)*norm.cdf(-d2)
               - q*St*math.exp(-q*T)*norm.cdf(-d1))/365
    rho_c   =  K*T*math.exp(-r*T)*norm.cdf(d2)/100
    rho_p   = -K*T*math.exp(-r*T)*norm.cdf(-d2)/100
    return dict(d1=d1,d2=d2,digit_call=dc,share_call=sc,digit_put=dp,share_put=sp,
                delta_c=delta_c,delta_p=delta_p,gamma=gamma,vega=vega,
                theta_c=theta_c,theta_p=theta_p,rho_c=rho_c,rho_p=rho_p)

def monte_carlo(St, K, sigma, T, r, reps=10000):
    np.random.seed(0)
    Z  = np.random.standard_normal(reps)
    ST = St * np.exp((r - 0.5*sigma**2)*T + sigma*np.sqrt(T)*Z)
    dc = np.exp(-r*T)*np.mean(ST > K)
    sc = np.exp(-r*T)*np.mean(np.maximum(ST-K,0))
    dp = np.exp(-r*T)*np.mean(ST < K)
    sp = np.exp(-r*T)*np.mean(np.maximum(K-ST,0))
    d1, d2 = bs_params(St, K, r, sigma, T)
    return dict(d1=d1,d2=d2,digit_call=dc,share_call=sc,digit_put=dp,share_put=sp,
                ST=ST, reps=reps)

def binomial_tree(St, K, sigma, T, r, N=100):
    dt = T/N
    u  = math.exp(sigma*math.sqrt(dt))
    d  = 1/u
    p  = (math.exp(r*dt)-d)/(u-d)
    ST = np.array([St*(u**j)*(d**(N-j)) for j in range(N+1)])
    cp = np.maximum(ST-K,0); pp = np.maximum(K-ST,0)
    dcp= (ST>K).astype(float); dpp=(ST<K).astype(float)
    for _ in range(N,0,-1):
        cp  = np.exp(-r*dt)*(p*cp[1:] +(1-p)*cp[:-1])
        pp  = np.exp(-r*dt)*(p*pp[1:] +(1-p)*pp[:-1])
        dcp = np.exp(-r*dt)*(p*dcp[1:]+(1-p)*dcp[:-1])
        dpp = np.exp(-r*dt)*(p*dpp[1:]+(1-p)*dpp[:-1])
    d1,d2 = bs_params(St, K, r, sigma, T)
    return dict(d1=d1,d2=d2,digit_call=dcp[0],share_call=cp[0],digit_put=dpp[0],share_put=pp[0])

# ── CHARTS ───────────────────────────────────────────────────
def payoff_chart(St, K, sigma, T, r, res):
    spots = np.linspace(St*0.5, St*1.5, 200)
    sc_vals, sp_vals, dc_vals, dp_vals = [],[],[],[]
    for s in spots:
        try:
            d1,d2 = bs_params(s,K,r,sigma,T)
            sc_vals.append(s*norm.cdf(d1) - K*math.exp(-r*T)*norm.cdf(d2))
            sp_vals.append(K*math.exp(-r*T)*norm.cdf(-d2) - s*norm.cdf(-d1))
            dc_vals.append(math.exp(-r*T)*norm.cdf(d2))
            dp_vals.append(math.exp(-r*T)*norm.cdf(-d2))
        except: sc_vals.append(0);sp_vals.append(0);dc_vals.append(0);dp_vals.append(0)

    fig = make_subplots(rows=1,cols=2,
        subplot_titles=["Share Options (Standard)", "Digital Options (Binary)"])
    fig.add_trace(go.Scatter(x=spots,y=sc_vals,name="Share Call",
        line=dict(color=C["green"],width=2)),row=1,col=1)
    fig.add_trace(go.Scatter(x=spots,y=sp_vals,name="Share Put",
        line=dict(color=C["red"],width=2)),row=1,col=1)
    fig.add_trace(go.Scatter(x=spots,y=dc_vals,name="Digital Call",
        line=dict(color=C["blue"],width=2,dash="dash")),row=1,col=2)
    fig.add_trace(go.Scatter(x=spots,y=dp_vals,name="Digital Put",
        line=dict(color=C["orange"],width=2,dash="dash")),row=1,col=2)
    for col in [1,2]:
        fig.add_vline(x=K, line=dict(color="#FFD700",dash="dot",width=1.5),
                      annotation_text="Strike K", annotation_font_color="#FFD700", row=1,col=col)
        fig.add_vline(x=St,line=dict(color="#555",   dash="dot",width=1),
                      annotation_text="Spot St",   annotation_font_color="#777",   row=1,col=col)
    fig.update_layout(template="plotly_dark",paper_bgcolor="#000",plot_bgcolor="#0D0D0D",
        height=400,legend=dict(orientation="h",x=0,y=1.12,font=dict(family="Courier New",size=10)),
        font=dict(family="Courier New",color="#777"),margin=dict(l=50,r=20,t=60,b=30))
    fig.update_xaxes(gridcolor="#1a1a1a",title_text="Spot Price")
    fig.update_yaxes(gridcolor="#1a1a1a",title_text="Option Price")
    return fig

def sensitivity_chart(St, K, sigma, T, r):
    sigmas = np.linspace(0.01, 0.80, 100)
    sc=[]; sp=[]; dc=[]; dp=[]
    for s in sigmas:
        try:
            r2=black_scholes(St,K,s,T,r)
            sc.append(r2["share_call"]); sp.append(r2["share_put"])
            dc.append(r2["digit_call"]); dp.append(r2["digit_put"])
        except: sc.append(0);sp.append(0);dc.append(0);dp.append(0)

    fig=make_subplots(rows=1,cols=2,subplot_titles=["Price vs Volatility (σ)","Digital Options vs Volatility (σ)"])
    fig.add_trace(go.Scatter(x=sigmas*100,y=sc,name="Share Call",line=dict(color=C["green"],width=2)),row=1,col=1)
    fig.add_trace(go.Scatter(x=sigmas*100,y=sp,name="Share Put", line=dict(color=C["red"],  width=2)),row=1,col=1)
    fig.add_trace(go.Scatter(x=sigmas*100,y=dc,name="Digital Call",line=dict(color=C["blue"],  width=2,dash="dash")),row=1,col=2)
    fig.add_trace(go.Scatter(x=sigmas*100,y=dp,name="Digital Put", line=dict(color=C["orange"],width=2,dash="dash")),row=1,col=2)
    fig.add_vline(x=sigma*100,line=dict(color="#FFD700",dash="dot",width=1.5),
                  annotation_text=f"σ={sigma:.0%}",annotation_font_color="#FFD700")
    fig.update_layout(template="plotly_dark",paper_bgcolor="#000",plot_bgcolor="#0D0D0D",
        height=400,legend=dict(orientation="h",x=0,y=1.12,font=dict(family="Courier New",size=10)),
        font=dict(family="Courier New",color="#777"),margin=dict(l=50,r=20,t=60,b=30))
    fig.update_xaxes(gridcolor="#1a1a1a",title_text="Volatility (%)")
    fig.update_yaxes(gridcolor="#1a1a1a",title_text="Option Price")
    return fig

def mc_distribution_chart(ST, K, St):
    fig = go.Figure()
    fig.add_trace(go.Histogram(x=ST, nbinsx=80, marker_color=C["blue"],
                               opacity=0.7, name="Simulated ST"))
    fig.add_vline(x=K,  line=dict(color=C["yellow"],dash="dot",width=2),
                  annotation_text=f"Strike K={K}", annotation_font_color=C["yellow"])
    fig.add_vline(x=St, line=dict(color=C["orange"],dash="dot",width=2),
                  annotation_text=f"Spot St={St}", annotation_font_color=C["orange"])
    itm_pct = np.mean(ST>K)*100
    fig.add_annotation(text=f"ITM (Call): {itm_pct:.1f}%",
        xref="paper",yref="paper",x=0.98,y=0.95,showarrow=False,
        font=dict(color=C["green"],size=13,family="Courier New"),align="right")
    fig.update_layout(template="plotly_dark",paper_bgcolor="#000",plot_bgcolor="#0D0D0D",
        height=380,title=dict(text="Monte Carlo — Simulated Terminal Price Distribution",
            font=dict(family="Courier New",size=13,color=C["orange"]),x=0),
        font=dict(family="Courier New",color="#777"),margin=dict(l=50,r=20,t=55,b=30),
        xaxis=dict(gridcolor="#1a1a1a",title="Terminal Price ST"),
        yaxis=dict(gridcolor="#1a1a1a",title="Frequency"))
    return fig

def greeks_chart(St, K, sigma, T, r):
    spots = np.linspace(St*0.5, St*1.5, 200)
    dc_vals=[]; dp_vals=[]; gc_vals=[]; vc_vals=[]
    for s in spots:
        try:
            res=black_scholes(s,K,sigma,T,r)
            dc_vals.append(res["delta_c"]); dp_vals.append(res["delta_p"])
            gc_vals.append(res["gamma"]);   vc_vals.append(res["vega"])
        except: dc_vals.append(0);dp_vals.append(0);gc_vals.append(0);vc_vals.append(0)
    fig=make_subplots(rows=1,cols=2,subplot_titles=["Delta","Gamma & Vega"])
    fig.add_trace(go.Scatter(x=spots,y=dc_vals,name="Δ Call",line=dict(color=C["green"],width=2)),row=1,col=1)
    fig.add_trace(go.Scatter(x=spots,y=dp_vals,name="Δ Put", line=dict(color=C["red"],  width=2)),row=1,col=1)
    fig.add_trace(go.Scatter(x=spots,y=gc_vals,name="Γ Gamma",line=dict(color=C["yellow"],width=2)),row=1,col=2)
    fig.add_trace(go.Scatter(x=spots,y=vc_vals,name="ν Vega", line=dict(color=C["blue"],  width=2,dash="dash")),row=1,col=2)
    for col in [1,2]:
        fig.add_vline(x=K, line=dict(color="#FFD700",dash="dot",width=1.5),row=1,col=col)
        fig.add_vline(x=St,line=dict(color="#555",   dash="dot",width=1),  row=1,col=col)
    fig.update_layout(template="plotly_dark",paper_bgcolor="#000",plot_bgcolor="#0D0D0D",
        height=400,legend=dict(orientation="h",x=0,y=1.12,font=dict(family="Courier New",size=10)),
        font=dict(family="Courier New",color="#777"),margin=dict(l=50,r=20,t=60,b=30))
    fig.update_xaxes(gridcolor="#1a1a1a",title_text="Spot Price")
    fig.update_yaxes(gridcolor="#1a1a1a")
    return fig

# ════════════════════════════════════════════════════════════
#  🚀  APP
# ════════════════════════════════════════════════════════════
st.markdown("""
<div style='background:#000;font-family:Courier New,monospace;padding:12px 20px;
            border-bottom:3px solid #FF6600;display:flex;justify-content:space-between;
            align-items:center;margin-bottom:14px'>
  <span style='color:#FF6600;font-size:20px;font-weight:bold;letter-spacing:3px'>
    ◈ OPTIONS PRICER  |  Black-Scholes · Monte Carlo · Binomial Tree
  </span>
  <span style='color:#00FF41;font-size:12px'>● LIVE CALCULATOR</span>
</div>""", unsafe_allow_html=True)

# ── SIDEBAR INPUTS ───────────────────────────────────────────
st.sidebar.markdown("""<p style='color:#FF6600;font-family:monospace;font-weight:bold;
font-size:16px;border-bottom:1px solid #FF6600;padding-bottom:6px'>⚙️ PARAMETERS</p>""",
unsafe_allow_html=True)

with st.sidebar:
    method = st.radio("Pricing Method",
                      ["Black-Scholes","Monte Carlo","Binomial Tree"], index=0)
    st.markdown("---")
    St    = st.number_input("St — Spot Price",    min_value=0.01, value=10.0,  step=0.5,  format="%.2f")
    K     = st.number_input("K  — Strike Price",  min_value=0.01, value=10.0,  step=0.5,  format="%.2f")
    sigma = st.slider("σ  — Volatility",          min_value=0.01, max_value=2.0, value=0.20, step=0.01, format="%.2f")
    T     = st.number_input("T  — Years to Expiry",min_value=0.01, value=1.0,  step=0.25, format="%.2f")
    r     = st.slider("r  — Risk-Free Rate",       min_value=0.00, max_value=0.30,value=0.05,step=0.005,format="%.3f")
    if method == "Black-Scholes":
        q = st.slider("q  — Dividend Yield",       min_value=0.00, max_value=0.20,value=0.0, step=0.005,format="%.3f")
    elif method == "Monte Carlo":
        reps = st.select_slider("Simulations",     options=[1000,5000,10000,50000,100000], value=10000)
    elif method == "Binomial Tree":
        N = st.select_slider("Tree Steps (N)",     options=[50,100,200,500,1000], value=100)
    st.markdown("---")
    run_btn = st.button("▶  CALCULATE", use_container_width=True)

# ── MONEYNESS BADGE ──────────────────────────────────────────
moneyness = "ATM ⚖️" if abs(St-K)<0.01*K else ("ITM 🟢" if St>K else "OTM 🔴")
intrinsic_c = max(St-K,0); intrinsic_p = max(K-St,0)
col_m = "#00FF41" if "ITM" in moneyness else ("#FFD700" if "ATM" in moneyness else "#FF3333")

st.markdown(f"""
<div style='display:flex;gap:16px;margin-bottom:14px;flex-wrap:wrap'>
  <div class='result-box' style='flex:1;min-width:140px'>
    <div style='color:#555;font-size:10px'>MONEYNESS</div>
    <div style='color:{col_m};font-size:22px;font-weight:bold'>{moneyness}</div>
  </div>
  <div class='result-box' style='flex:1;min-width:140px'>
    <div style='color:#555;font-size:10px'>INTRINSIC VALUE (CALL)</div>
    <div style='color:#FFD700;font-size:22px;font-weight:bold'>{intrinsic_c:.4f}</div>
  </div>
  <div class='result-box' style='flex:1;min-width:140px'>
    <div style='color:#555;font-size:10px'>INTRINSIC VALUE (PUT)</div>
    <div style='color:#FFD700;font-size:22px;font-weight:bold'>{intrinsic_p:.4f}</div>
  </div>
  <div class='result-box' style='flex:1;min-width:140px'>
    <div style='color:#555;font-size:10px'>METHOD</div>
    <div style='color:#FF6600;font-size:16px;font-weight:bold'>{method}</div>
  </div>
</div>""", unsafe_allow_html=True)

# ── RESULTS ──────────────────────────────────────────────────
if run_btn or True:  # auto-run on load
    try:
        if method == "Black-Scholes":
            res = black_scholes(St, K, sigma, T, r, q)
        elif method == "Monte Carlo":
            res = monte_carlo(St, K, sigma, T, r, reps)
        else:
            res = binomial_tree(St, K, sigma, T, r, N)

        tab1,tab2,tab3,tab4 = st.tabs(["📐 PRICES","📊 PAYOFF CHART","📈 GREEKS","🔬 SENSITIVITY"])

        with tab1:
            st.markdown("### Option Prices")
            c1,c2,c3,c4,c5,c6 = st.columns(6)
            def metric_card(col, label, value, color="#FFD700", hint=""):
                col.markdown(f"""
                <div class='result-box' style='text-align:center'>
                  <div style='color:#555;font-size:10px;margin-bottom:4px'>{label}</div>
                  <div style='color:{color};font-size:20px;font-weight:bold'>{value:.5f}</div>
                  {"<div style='color:#444;font-size:9px;margin-top:4px'>"+hint+"</div>" if hint else ""}
                </div>""", unsafe_allow_html=True)
            metric_card(c1,"d1",         res["d1"],         "#00BFFF","N(d1) prob factor")
            metric_card(c2,"d2",         res["d2"],         "#00BFFF","N(d2) risk-neutral prob")
            metric_card(c3,"DIGITAL CALL",res["digit_call"],C["green"],"Binary call price")
            metric_card(c4,"SHARE CALL", res["share_call"], C["green"],"Vanilla call price")
            metric_card(c5,"DIGITAL PUT", res["digit_put"], C["red"],  "Binary put price")
            metric_card(c6,"SHARE PUT",  res["share_put"],  C["red"],  "Vanilla put price")

            # Put-Call Parity check
            parity_check = res["share_call"] - res["share_put"] - (St - K*math.exp(-r*T))
            ok = abs(parity_check) < 0.001
            st.markdown(f"""
            <div style='margin-top:14px;padding:10px 16px;background:#0D0D0D;
                         border-left:3px solid {"#00FF41" if ok else "#FF3333"};
                         font-family:Courier New,monospace;font-size:12px'>
              <span style='color:#FF6600;font-weight:bold'>PUT-CALL PARITY CHECK: </span>
              <span style='color:{"#00FF41" if ok else "#FF3333"}'>
                C - P = {res['share_call']:.5f} - {res['share_put']:.5f} = {res['share_call']-res['share_put']:.5f}
                &nbsp;|&nbsp; S - Ke⁻ʳᵀ = {St - K*math.exp(-r*T):.5f}
                &nbsp;|&nbsp; Error = {parity_check:.6f} {"✅ VALID" if ok else "⚠️ CHECK INPUTS"}
              </span>
            </div>""", unsafe_allow_html=True)

            # Greeks (Black-Scholes only)
            if method == "Black-Scholes":
                st.markdown("### Option Greeks")
                g1,g2,g3,g4,g5,g6,g7,g8 = st.columns(8)
                metric_card(g1,"Δ CALL",  res["delta_c"],C["green"])
                metric_card(g2,"Δ PUT",   res["delta_p"],C["red"])
                metric_card(g3,"Γ GAMMA", res["gamma"],  C["yellow"])
                metric_card(g4,"ν VEGA",  res["vega"],   C["blue"])
                metric_card(g5,"Θ CALL/day",res["theta_c"],C["orange"])
                metric_card(g6,"Θ PUT/day", res["theta_p"],C["orange"])
                metric_card(g7,"ρ CALL",  res["rho_c"],  "#aaaaaa")
                metric_card(g8,"ρ PUT",   res["rho_p"],  "#aaaaaa")

            # MC distribution
            if method == "Monte Carlo" and "ST" in res:
                st.markdown("### Simulation Distribution")
                st.plotly_chart(mc_distribution_chart(res["ST"], K, St),
                                use_container_width=True)
                st.markdown(f"""
                <div style='font-family:Courier New,monospace;color:#555;font-size:11px;padding:6px 0'>
                  Simulations: {res['reps']:,}  |  Seed: 0 (reproducible)  |
                  ITM (Call): {np.mean(res['ST']>K):.2%}  |  ITM (Put): {np.mean(res['ST']<K):.2%}
                </div>""", unsafe_allow_html=True)

            # Comparison table across all methods
            st.markdown("### Method Comparison")
            with st.spinner("Running all 3 methods for comparison..."):
                bs  = black_scholes(St, K, sigma, T, r, 0)
                mc  = monte_carlo(St,  K, sigma, T, r, 10000)
                bt  = binomial_tree(St, K, sigma, T, r, 100)
                comp = pd.DataFrame({
                    "Method":       ["Black-Scholes","Monte Carlo (10k)","Binomial Tree (N=100)"],
                    "Digital Call": [f"{bs['digit_call']:.5f}",f"{mc['digit_call']:.5f}",f"{bt['digit_call']:.5f}"],
                    "Share Call":   [f"{bs['share_call']:.5f}", f"{mc['share_call']:.5f}", f"{bt['share_call']:.5f}"],
                    "Digital Put":  [f"{bs['digit_put']:.5f}",  f"{mc['digit_put']:.5f}",  f"{bt['digit_put']:.5f}"],
                    "Share Put":    [f"{bs['share_put']:.5f}",  f"{mc['share_put']:.5f}",  f"{bt['share_put']:.5f}"],
                })
                st.dataframe(comp.set_index("Method"), use_container_width=True)

        with tab2:
            st.markdown("### Payoff Diagrams vs Spot Price")
            st.plotly_chart(payoff_chart(St, K, sigma, T, r, res),
                            use_container_width=True)

        with tab3:
            st.markdown("### Greeks vs Spot Price (Black-Scholes)")
            st.plotly_chart(greeks_chart(St, K, sigma, T, r),
                            use_container_width=True)
            st.markdown(f"""
            <div style='font-family:Courier New,monospace;font-size:11px;color:#555;
                         padding:8px;background:#0D0D0D;border-radius:4px'>
              <b style='color:#FF6600'>GREEKS LEGEND:</b>&nbsp;
              <span style='color:#00FF41'>Δ Delta</span> = sensitivity to spot price &nbsp;|&nbsp;
              <span style='color:#FFD700'>Γ Gamma</span> = rate of change of delta &nbsp;|&nbsp;
              <span style='color:#00BFFF'>ν Vega</span> = sensitivity to volatility (per 1% σ) &nbsp;|&nbsp;
              <span style='color:#FF6600'>Θ Theta</span> = time decay (per day)
            </div>""", unsafe_allow_html=True)

        with tab4:
            st.markdown("### Price Sensitivity to Volatility (σ)")
            st.plotly_chart(sensitivity_chart(St, K, sigma, T, r),
                            use_container_width=True)

            # Time sensitivity
            st.markdown("### Price Sensitivity to Time to Expiry (T)")
            times = np.linspace(0.05, 3.0, 100)
            tc_=[]; tp_=[]; tdc_=[]; tdp_=[]
            for t in times:
                try:
                    rr=black_scholes(St,K,sigma,t,r)
                    tc_.append(rr["share_call"]); tp_.append(rr["share_put"])
                    tdc_.append(rr["digit_call"]); tdp_.append(rr["digit_put"])
                except: tc_.append(0);tp_.append(0);tdc_.append(0);tdp_.append(0)
            fig2=make_subplots(rows=1,cols=2,subplot_titles=["Share Options vs Time","Digital Options vs Time"])
            fig2.add_trace(go.Scatter(x=times,y=tc_,name="Share Call",line=dict(color=C["green"],width=2)),row=1,col=1)
            fig2.add_trace(go.Scatter(x=times,y=tp_,name="Share Put", line=dict(color=C["red"],  width=2)),row=1,col=1)
            fig2.add_trace(go.Scatter(x=times,y=tdc_,name="Digital Call",line=dict(color=C["blue"],  width=2,dash="dash")),row=1,col=2)
            fig2.add_trace(go.Scatter(x=times,y=tdp_,name="Digital Put", line=dict(color=C["orange"],width=2,dash="dash")),row=1,col=2)
            for col in [1,2]:
                fig2.add_vline(x=T,line=dict(color="#FFD700",dash="dot",width=1.5),
                               annotation_text=f"T={T}y",annotation_font_color="#FFD700",row=1,col=col)
            fig2.update_layout(template="plotly_dark",paper_bgcolor="#000",plot_bgcolor="#0D0D0D",
                height=380,legend=dict(orientation="h",x=0,y=1.12,font=dict(family="Courier New",size=10)),
                font=dict(family="Courier New",color="#777"),margin=dict(l=50,r=20,t=60,b=30))
            fig2.update_xaxes(gridcolor="#1a1a1a",title_text="Time to Expiry (years)")
            fig2.update_yaxes(gridcolor="#1a1a1a",title_text="Option Price")
            st.plotly_chart(fig2, use_container_width=True)

    except Exception as e:
        st.error(f"❌ Calculation error: {e}")
        st.info("💡 Check your inputs — T must be > 0 and σ must be > 0.")

st.markdown("""
<div style='font-family:Courier New,monospace;font-size:10px;color:#333;
             text-align:center;padding:20px 0;border-top:1px solid #1a1a1a;margin-top:20px'>
  ◈ OPTIONS PRICER  |  Black-Scholes · Monte Carlo · Binomial Tree  |  Built with Python + Streamlit
</div>""", unsafe_allow_html=True)